### ISSUE TITLE
ImportError: No module named 'celery_tests'

### ISSUE THREAD

**Issue by Avin-Techv** [trthhrtz/celery_example#1]
Traceback (most recent call last):
  File "/home/techv/Desktop/celery_example/env/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/home/techv/Desktop/celery_example/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'celery_tests'

**Comment by techkuz** [comment]
@Avin-Techv thanks. Fixed
